static const uint3 gl_WorkGroupSize = uint3(4u, 1u, 1u);

void comp_main()
{
    DeviceMemoryBarrier();
    DeviceMemoryBarrier();
    DeviceMemoryBarrier();
    DeviceMemoryBarrier();
    DeviceMemoryBarrier();
    DeviceMemoryBarrierWithGroupSync();
    DeviceMemoryBarrier();
    DeviceMemoryBarrierWithGroupSync();
    DeviceMemoryBarrier();
    DeviceMemoryBarrierWithGroupSync();
    DeviceMemoryBarrier();
    DeviceMemoryBarrierWithGroupSync();
    DeviceMemoryBarrier();
    DeviceMemoryBarrierWithGroupSync();
    DeviceMemoryBarrierWithGroupSync();
}

[numthreads(4, 1, 1)]
void main()
{
    comp_main();
}
