struct SSBO
{
    float4 data[1];
};

RWStructuredBuffer<SSBO> ssbos : register(u0);

static uint3 gl_GlobalInvocationID;
struct SPIRV_Cross_Input
{
    uint3 gl_GlobalInvocationID : SV_DispatchThreadID;
};

void comp_main()
{
    uint ident = gl_GlobalInvocationID.x;
    ssbos[1].data[ident] = ssbos[0].data[ident];
}

[numthreads(1, 1, 1)]
void main(SPIRV_Cross_Input stage_input)
{
    gl_GlobalInvocationID = stage_input.gl_GlobalInvocationID;
    comp_main();
}
