#version 310 es
layout(local_size_x = 4) in;

void barrier_shared()
{
	memoryBarrierShared();
}

void full_barrier()
{
	memoryBarrier();
}

void image_barrier()
{
	memoryBarrierImage();
}

void buffer_barrier()
{
	memoryBarrierBuffer();
}

void group_barrier()
{
	groupMemoryBarrier();
}

void exec_barrier()
{
	barrier();
}

void main()
{
	barrier_shared();
	full_barrier();
	image_barrier();
	buffer_barrier();
	group_barrier();
	exec_barrier();
}
