#include <metal_stdlib>
#include <simd/simd.h>

using namespace metal;

struct myBlock
{
    int a;
    float b[1];
};

kernel void main0(device myBlock& myStorage [[buffer(0)]], uint3 gl_GlobalInvocationID [[thread_position_in_grid]])
{
    int _19 = myStorage.a + 1;
    myStorage.a = (_19 - 256 * (_19 / 256) + 256) - 256 * ((_19 - 256 * (_19 / 256) + 256) / 256);
    myStorage.b[gl_GlobalInvocationID.x] += 0.0199999995529651641845703125;
}

